### ISSUE TITLE
Method for specifying space orientation

### ISSUE THREAD

**Issue by PolarBean** [blixilla/LocareJSON#8]
Good update specifying the orientation of the space (ie; https://github.com/blixilla/LocareJSON/blob/main/examples/Raw_Data_Sleep.json#L10C1-L10C93)

One suggestion I have is to use standardised terms for the orientation.
http://www.grahamwideman.com/gw/brain/orientation/orientterms.htm

Most tools will encode direction of a space in the following way

left and right relative to the midline of the brain: Left or Right
front of nose to back of head: Anterior or Posterior
top of head to bottom: Superior or Inferior 

You then take the first letter of each choice to make an orientation code (ie; commonly volumes are assumed RAS by default)

Since each letter also refers to a unique dimension you can also mix them if a volume has a different axis order (ARS is valid)
for more examples see here: 
https://pypi.org/project/reorient-nii/

**Comment by blixilla** [comment]
Thank you, addressed in 46ac8fb2b3daa695087251faa71dbd10849ecce3
