### ISSUE TITLE
Machine readable resolution for sphere calculation

### ISSUE THREAD

**Issue by olinux** [blixilla/LocareJSON#9]
I assume, the resolution as specified here:
https://github.com/blixilla/LocareJSON/blob/25db64186405f45926cec69612c048b37160e7e0/examples/EEG.json#L9C12-L9C34
is meant to reflect the size of a coordinate unit. Is this assumption correct?

For more simple interpretation, it would be nice to:
- have the resolution as a number instead of a string and therefore to split this information as it is currently done in radius for sphere
- have a normalized unit for the full document (e.g. if the resolution is defined in "μm", the radius should be kept in the same unit. Otherwise, the burden of translation of units is put on the consuming client. I therefore would suggest to remove the "unit" from the "radius" and specify that the unit of the radius is always the same as the resolution of the target atlas

**Comment by aeidi89** [comment]
Hi @olinux 
Your assumption will in general be correct.
I agree with your suggestions for a simpler interpretation.

Is it possible for you to create a PR where your suggestion to represent resolution as a number is implemented?

**Comment by blixilla** [comment]
Thanks for the input @olinux and @aeidi89,
I agree in making the schemas more machine readable. However, I'm afraid that omitting the unit from e.g. radius could cause confusion as it is not immediately obvious that the unit in the schema metadata would also apply to the content. Therefore, I want to keep it, even though it would most often be redundant.

I will release a new version where unit and value for resolution is defined separately in the metadata. I'll also update the examples. Examples adhering to v1.0.0 of the schema can still be found, [under the corresponding tag].(https://github.com/blixilla/LocareJSON/tree/v1.0.0/examples).

**Comment by blixilla** [comment]
Resolved in latest release (v1.1.0)
